// GENERATED by scripts/generate-mortgage-rates.ts — do not edit by hand.
//
// Bank of Ireland's published mortgage rate table, read from their site on
// 2026-10-09. The table labels its own last update as
// 2025-11-26T08:17:48, and that date is carried through to
// everything Baz says about a rate: a figure without an as-of is a figure nobody can check.
//
// 133 rows, because a rate here is a function of four things at once —
// who the customer is, the BER of the property, the term, and how much they are borrowing.
// Picking the right one is `selectRates` in `mortgage-rates-select.ts`, deliberately not
// something the model does by reading a table.

import type { MortgageRateCatalogue } from './mortgage-rate-types.ts'

export const boiMortgageRates = {
  "metadata": {
    "name": "Bank of Ireland Mortgage Rates Knowledge Base for Baz",
    "version": "1.0",
    "retrieved_on": "2026-10-09",
    "public_rates_table_last_update": "2025-11-26T08:17:48",
    "source_url": "https://personalbanking.bankofireland.com/borrow/mortgages/mortgage-interest-rates/",
    "important_freshness_note": "The official BOI rate table was fetched on 2026-10-09 but labels its own last update as 26 November 2025. Treat this file as a snapshot of what BOI currently publishes, not a substitute for a live source-of-truth feed.",
    "ber_scale_note": "BOI states that a new BER scale introduced on 24 May 2026 uses A0, A, B, C, D, E, F and G. The current mortgage-rate table still exposes A through G plus BER Exempt (and No BER for some existing-customer rows). Do not infer an A0 rate from A without a live/authoritative mapping."
  },
  "product_rules": {
    "high_value_mortgage": {
      "minimum_mortgage_amount_eur": 250000,
      "fixed_terms_years": [
        1,
        4,
        5,
        7
      ],
      "cashback_available": false,
      "eligible_summary": "Buying/building an owner-occupied home or switching from another lender outside Bank of Ireland Group; borrowing €250,000+."
    },
    "cashback_plus": {
      "eligible_customer_types": [
        "first_time_buyer",
        "mover",
        "switcher"
      ],
      "eligible_summary": "Qualifying new fixed-rate mortgages.",
      "structure": "2% of mortgage drawdown after drawdown + 1% after 5 years subject to conditions.",
      "not_available_on": [
        "high_value_mortgage",
        "standard_variable"
      ]
    },
    "ecosaver": {
      "available_on": "fixed rates only",
      "principle": "Better BER gives a lower EcoSaver fixed rate.",
      "valid_ber_required": true,
      "eligible_summary": "FTBs, movers, switchers, investment-property buyers and qualifying existing customers.",
      "rate_change_after_upgrade": "Existing EcoSaver customers may qualify for a better discount if BER improves by at least one full letter, subject to terms."
    },
    "equity_release": {
      "rates_filter_rule": "BOI instructs existing customers moving home or applying for equity release to use the Mover rate filter.",
      "cashback": "2% on qualifying fixed-rate equity release drawdown; no cashback on HVM or standard variable."
    },
    "aprc_context": "BOI states APRC calculations are based on a €100,000 mortgage over 20 years and include stated mortgage/valuation charges. Do not use APRC as the customer's actual monthly repayment rate."
  },
  "baz_answering_rules": [
    "Before quoting a rate, establish mortgage type (FTB, mover, switcher, existing BOI mortgage, buy-to-let), BER and—where HVM may apply—mortgage amount.",
    "For a new owner-occupier borrowing €250,000+, compare HVM/no-cashback against qualifying cashback fixed rates rather than automatically calling the lower headline rate better.",
    "Quote both interest rate and APRC when available, and distinguish them clearly.",
    "If BER is A0, do not map it to A from this snapshot; request a live rate lookup.",
    "For exact customer-facing answers in production, refresh from an authoritative BOI rate service/page at response time.",
    "Never imply approval or eligibility merely because a published rate exists."
  ],
  "rates": [
    {
      "id": "new.standard.2y.a",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "standard_fixed_cashback",
      "term_years": 2,
      "ber": "A",
      "interest_rate_pct": 3.8,
      "aprc_pct": 4.2,
      "cashback": {
        "eligible": true,
        "structure": "2% after drawdown + 1% after 5 years subject to conditions"
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "new.standard.2y.b",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "standard_fixed_cashback",
      "term_years": 2,
      "ber": "B",
      "interest_rate_pct": 3.85,
      "aprc_pct": 4.2,
      "cashback": {
        "eligible": true,
        "structure": "2% after drawdown + 1% after 5 years subject to conditions"
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "new.standard.2y.c",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "standard_fixed_cashback",
      "term_years": 2,
      "ber": "C",
      "interest_rate_pct": 3.9,
      "aprc_pct": 4.2,
      "cashback": {
        "eligible": true,
        "structure": "2% after drawdown + 1% after 5 years subject to conditions"
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "new.standard.2y.d",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "standard_fixed_cashback",
      "term_years": 2,
      "ber": "D",
      "interest_rate_pct": 3.95,
      "aprc_pct": 4.2,
      "cashback": {
        "eligible": true,
        "structure": "2% after drawdown + 1% after 5 years subject to conditions"
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "new.standard.2y.e",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "standard_fixed_cashback",
      "term_years": 2,
      "ber": "E",
      "interest_rate_pct": 4,
      "aprc_pct": 4.2,
      "cashback": {
        "eligible": true,
        "structure": "2% after drawdown + 1% after 5 years subject to conditions"
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "new.standard.2y.f",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "standard_fixed_cashback",
      "term_years": 2,
      "ber": "F",
      "interest_rate_pct": 4.05,
      "aprc_pct": 4.2,
      "cashback": {
        "eligible": true,
        "structure": "2% after drawdown + 1% after 5 years subject to conditions"
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "new.standard.2y.g",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "standard_fixed_cashback",
      "term_years": 2,
      "ber": "G",
      "interest_rate_pct": 4.1,
      "aprc_pct": 4.2,
      "cashback": {
        "eligible": true,
        "structure": "2% after drawdown + 1% after 5 years subject to conditions"
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "new.standard.2y.ber_exempt",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "standard_fixed_cashback",
      "term_years": 2,
      "ber": "BER Exempt",
      "interest_rate_pct": 4.15,
      "aprc_pct": 4.3,
      "cashback": {
        "eligible": true,
        "structure": "2% after drawdown + 1% after 5 years subject to conditions"
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "new.standard.3y.a",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "standard_fixed_cashback",
      "term_years": 3,
      "ber": "A",
      "interest_rate_pct": 3.9,
      "aprc_pct": 4.2,
      "cashback": {
        "eligible": true,
        "structure": "2% after drawdown + 1% after 5 years subject to conditions"
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "new.standard.3y.b",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "standard_fixed_cashback",
      "term_years": 3,
      "ber": "B",
      "interest_rate_pct": 3.95,
      "aprc_pct": 4.2,
      "cashback": {
        "eligible": true,
        "structure": "2% after drawdown + 1% after 5 years subject to conditions"
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "new.standard.3y.c",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "standard_fixed_cashback",
      "term_years": 3,
      "ber": "C",
      "interest_rate_pct": 4,
      "aprc_pct": 4.2,
      "cashback": {
        "eligible": true,
        "structure": "2% after drawdown + 1% after 5 years subject to conditions"
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "new.standard.3y.d",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "standard_fixed_cashback",
      "term_years": 3,
      "ber": "D",
      "interest_rate_pct": 4.05,
      "aprc_pct": 4.2,
      "cashback": {
        "eligible": true,
        "structure": "2% after drawdown + 1% after 5 years subject to conditions"
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "new.standard.3y.e",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "standard_fixed_cashback",
      "term_years": 3,
      "ber": "E",
      "interest_rate_pct": 4.1,
      "aprc_pct": 4.2,
      "cashback": {
        "eligible": true,
        "structure": "2% after drawdown + 1% after 5 years subject to conditions"
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "new.standard.3y.f",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "standard_fixed_cashback",
      "term_years": 3,
      "ber": "F",
      "interest_rate_pct": 4.15,
      "aprc_pct": 4.3,
      "cashback": {
        "eligible": true,
        "structure": "2% after drawdown + 1% after 5 years subject to conditions"
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "new.standard.3y.g",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "standard_fixed_cashback",
      "term_years": 3,
      "ber": "G",
      "interest_rate_pct": 4.2,
      "aprc_pct": 4.3,
      "cashback": {
        "eligible": true,
        "structure": "2% after drawdown + 1% after 5 years subject to conditions"
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "new.standard.3y.ber_exempt",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "standard_fixed_cashback",
      "term_years": 3,
      "ber": "BER Exempt",
      "interest_rate_pct": 4.25,
      "aprc_pct": 4.4,
      "cashback": {
        "eligible": true,
        "structure": "2% after drawdown + 1% after 5 years subject to conditions"
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "new.standard.5y.a",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "standard_fixed_cashback",
      "term_years": 5,
      "ber": "A",
      "interest_rate_pct": 3.9,
      "aprc_pct": 4.1,
      "cashback": {
        "eligible": true,
        "structure": "2% after drawdown + 1% after 5 years subject to conditions"
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "new.standard.5y.b",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "standard_fixed_cashback",
      "term_years": 5,
      "ber": "B",
      "interest_rate_pct": 3.95,
      "aprc_pct": 4.2,
      "cashback": {
        "eligible": true,
        "structure": "2% after drawdown + 1% after 5 years subject to conditions"
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "new.standard.5y.c",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "standard_fixed_cashback",
      "term_years": 5,
      "ber": "C",
      "interest_rate_pct": 4,
      "aprc_pct": 4.2,
      "cashback": {
        "eligible": true,
        "structure": "2% after drawdown + 1% after 5 years subject to conditions"
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "new.standard.5y.d",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "standard_fixed_cashback",
      "term_years": 5,
      "ber": "D",
      "interest_rate_pct": 4.05,
      "aprc_pct": 4.2,
      "cashback": {
        "eligible": true,
        "structure": "2% after drawdown + 1% after 5 years subject to conditions"
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "new.standard.5y.e",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "standard_fixed_cashback",
      "term_years": 5,
      "ber": "E",
      "interest_rate_pct": 4.1,
      "aprc_pct": 4.2,
      "cashback": {
        "eligible": true,
        "structure": "2% after drawdown + 1% after 5 years subject to conditions"
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "new.standard.5y.f",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "standard_fixed_cashback",
      "term_years": 5,
      "ber": "F",
      "interest_rate_pct": 4.15,
      "aprc_pct": 4.3,
      "cashback": {
        "eligible": true,
        "structure": "2% after drawdown + 1% after 5 years subject to conditions"
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "new.standard.5y.g",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "standard_fixed_cashback",
      "term_years": 5,
      "ber": "G",
      "interest_rate_pct": 4.2,
      "aprc_pct": 4.3,
      "cashback": {
        "eligible": true,
        "structure": "2% after drawdown + 1% after 5 years subject to conditions"
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "new.standard.5y.ber_exempt",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "standard_fixed_cashback",
      "term_years": 5,
      "ber": "BER Exempt",
      "interest_rate_pct": 4.25,
      "aprc_pct": 4.4,
      "cashback": {
        "eligible": true,
        "structure": "2% after drawdown + 1% after 5 years subject to conditions"
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "new.standard.10y.a",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "standard_fixed_cashback",
      "term_years": 10,
      "ber": "A",
      "interest_rate_pct": 4.2,
      "aprc_pct": 4.3,
      "cashback": {
        "eligible": true,
        "structure": "2% after drawdown + 1% after 5 years subject to conditions"
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "new.standard.10y.b",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "standard_fixed_cashback",
      "term_years": 10,
      "ber": "B",
      "interest_rate_pct": 4.25,
      "aprc_pct": 4.4,
      "cashback": {
        "eligible": true,
        "structure": "2% after drawdown + 1% after 5 years subject to conditions"
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "new.standard.10y.c",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "standard_fixed_cashback",
      "term_years": 10,
      "ber": "C",
      "interest_rate_pct": 4.3,
      "aprc_pct": 4.4,
      "cashback": {
        "eligible": true,
        "structure": "2% after drawdown + 1% after 5 years subject to conditions"
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "new.standard.10y.d",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "standard_fixed_cashback",
      "term_years": 10,
      "ber": "D",
      "interest_rate_pct": 4.35,
      "aprc_pct": 4.5,
      "cashback": {
        "eligible": true,
        "structure": "2% after drawdown + 1% after 5 years subject to conditions"
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "new.standard.10y.e",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "standard_fixed_cashback",
      "term_years": 10,
      "ber": "E",
      "interest_rate_pct": 4.4,
      "aprc_pct": 4.5,
      "cashback": {
        "eligible": true,
        "structure": "2% after drawdown + 1% after 5 years subject to conditions"
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "new.standard.10y.f",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "standard_fixed_cashback",
      "term_years": 10,
      "ber": "F",
      "interest_rate_pct": 4.45,
      "aprc_pct": 4.6,
      "cashback": {
        "eligible": true,
        "structure": "2% after drawdown + 1% after 5 years subject to conditions"
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "new.standard.10y.g",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "standard_fixed_cashback",
      "term_years": 10,
      "ber": "G",
      "interest_rate_pct": 4.5,
      "aprc_pct": 4.6,
      "cashback": {
        "eligible": true,
        "structure": "2% after drawdown + 1% after 5 years subject to conditions"
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "new.standard.10y.ber_exempt",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "standard_fixed_cashback",
      "term_years": 10,
      "ber": "BER Exempt",
      "interest_rate_pct": 4.55,
      "aprc_pct": 4.7,
      "cashback": {
        "eligible": true,
        "structure": "2% after drawdown + 1% after 5 years subject to conditions"
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "hvm.1y.a",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "high_value_fixed",
      "term_years": 1,
      "ber": "A",
      "interest_rate_pct": 3.3,
      "aprc_pct": 4.2,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": 250000,
      "notes": [
        "Owner-occupier buying/building or switching from a lender outside Bank of Ireland Group."
      ]
    },
    {
      "id": "hvm.1y.b",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "high_value_fixed",
      "term_years": 1,
      "ber": "B",
      "interest_rate_pct": 3.35,
      "aprc_pct": 4.2,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": 250000,
      "notes": [
        "Owner-occupier buying/building or switching from a lender outside Bank of Ireland Group."
      ]
    },
    {
      "id": "hvm.1y.c",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "high_value_fixed",
      "term_years": 1,
      "ber": "C",
      "interest_rate_pct": 3.4,
      "aprc_pct": 4.2,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": 250000,
      "notes": [
        "Owner-occupier buying/building or switching from a lender outside Bank of Ireland Group."
      ]
    },
    {
      "id": "hvm.1y.d",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "high_value_fixed",
      "term_years": 1,
      "ber": "D",
      "interest_rate_pct": 3.45,
      "aprc_pct": 4.2,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": 250000,
      "notes": [
        "Owner-occupier buying/building or switching from a lender outside Bank of Ireland Group."
      ]
    },
    {
      "id": "hvm.1y.e",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "high_value_fixed",
      "term_years": 1,
      "ber": "E",
      "interest_rate_pct": 3.5,
      "aprc_pct": 4.2,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": 250000,
      "notes": [
        "Owner-occupier buying/building or switching from a lender outside Bank of Ireland Group."
      ]
    },
    {
      "id": "hvm.1y.f",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "high_value_fixed",
      "term_years": 1,
      "ber": "F",
      "interest_rate_pct": 3.55,
      "aprc_pct": 4.2,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": 250000,
      "notes": [
        "Owner-occupier buying/building or switching from a lender outside Bank of Ireland Group."
      ]
    },
    {
      "id": "hvm.1y.g",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "high_value_fixed",
      "term_years": 1,
      "ber": "G",
      "interest_rate_pct": 3.6,
      "aprc_pct": 4.2,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": 250000,
      "notes": [
        "Owner-occupier buying/building or switching from a lender outside Bank of Ireland Group."
      ]
    },
    {
      "id": "hvm.1y.ber_exempt",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "high_value_fixed",
      "term_years": 1,
      "ber": "BER Exempt",
      "interest_rate_pct": 3.65,
      "aprc_pct": 4.2,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": 250000,
      "notes": [
        "Owner-occupier buying/building or switching from a lender outside Bank of Ireland Group."
      ]
    },
    {
      "id": "hvm.4y.a",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "high_value_fixed",
      "term_years": 4,
      "ber": "A",
      "interest_rate_pct": 3.1,
      "aprc_pct": 3.8,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": 250000,
      "notes": []
    },
    {
      "id": "hvm.4y.b",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "high_value_fixed",
      "term_years": 4,
      "ber": "B",
      "interest_rate_pct": 3.15,
      "aprc_pct": 3.8,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": 250000,
      "notes": []
    },
    {
      "id": "hvm.4y.c",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "high_value_fixed",
      "term_years": 4,
      "ber": "C",
      "interest_rate_pct": 3.2,
      "aprc_pct": 3.9,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": 250000,
      "notes": []
    },
    {
      "id": "hvm.4y.d",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "high_value_fixed",
      "term_years": 4,
      "ber": "D",
      "interest_rate_pct": 3.25,
      "aprc_pct": 3.9,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": 250000,
      "notes": []
    },
    {
      "id": "hvm.4y.e",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "high_value_fixed",
      "term_years": 4,
      "ber": "E",
      "interest_rate_pct": 3.3,
      "aprc_pct": 3.9,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": 250000,
      "notes": []
    },
    {
      "id": "hvm.4y.f",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "high_value_fixed",
      "term_years": 4,
      "ber": "F",
      "interest_rate_pct": 3.35,
      "aprc_pct": 3.9,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": 250000,
      "notes": []
    },
    {
      "id": "hvm.4y.g",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "high_value_fixed",
      "term_years": 4,
      "ber": "G",
      "interest_rate_pct": 3.4,
      "aprc_pct": 3.9,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": 250000,
      "notes": []
    },
    {
      "id": "hvm.4y.ber_exempt",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "high_value_fixed",
      "term_years": 4,
      "ber": "BER Exempt",
      "interest_rate_pct": 3.45,
      "aprc_pct": 4,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": 250000,
      "notes": []
    },
    {
      "id": "hvm.5y.a",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "high_value_fixed",
      "term_years": 5,
      "ber": "A",
      "interest_rate_pct": 3.4,
      "aprc_pct": 3.9,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": 250000,
      "notes": []
    },
    {
      "id": "hvm.5y.b",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "high_value_fixed",
      "term_years": 5,
      "ber": "B",
      "interest_rate_pct": 3.45,
      "aprc_pct": 3.9,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": 250000,
      "notes": []
    },
    {
      "id": "hvm.5y.c",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "high_value_fixed",
      "term_years": 5,
      "ber": "C",
      "interest_rate_pct": 3.5,
      "aprc_pct": 3.9,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": 250000,
      "notes": []
    },
    {
      "id": "hvm.5y.d",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "high_value_fixed",
      "term_years": 5,
      "ber": "D",
      "interest_rate_pct": 3.55,
      "aprc_pct": 4,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": 250000,
      "notes": []
    },
    {
      "id": "hvm.5y.e",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "high_value_fixed",
      "term_years": 5,
      "ber": "E",
      "interest_rate_pct": 3.6,
      "aprc_pct": 4,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": 250000,
      "notes": []
    },
    {
      "id": "hvm.5y.f",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "high_value_fixed",
      "term_years": 5,
      "ber": "F",
      "interest_rate_pct": 3.65,
      "aprc_pct": 4,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": 250000,
      "notes": []
    },
    {
      "id": "hvm.5y.g",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "high_value_fixed",
      "term_years": 5,
      "ber": "G",
      "interest_rate_pct": 3.7,
      "aprc_pct": 4,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": 250000,
      "notes": []
    },
    {
      "id": "hvm.5y.ber_exempt",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "high_value_fixed",
      "term_years": 5,
      "ber": "BER Exempt",
      "interest_rate_pct": 3.75,
      "aprc_pct": 4.1,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": 250000,
      "notes": []
    },
    {
      "id": "hvm.7y.a",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "high_value_fixed",
      "term_years": 7,
      "ber": "A",
      "interest_rate_pct": 3.45,
      "aprc_pct": 3.8,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": 250000,
      "notes": []
    },
    {
      "id": "hvm.7y.b",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "high_value_fixed",
      "term_years": 7,
      "ber": "B",
      "interest_rate_pct": 3.5,
      "aprc_pct": 3.8,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": 250000,
      "notes": []
    },
    {
      "id": "hvm.7y.c",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "high_value_fixed",
      "term_years": 7,
      "ber": "C",
      "interest_rate_pct": 3.55,
      "aprc_pct": 3.9,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": 250000,
      "notes": []
    },
    {
      "id": "hvm.7y.d",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "high_value_fixed",
      "term_years": 7,
      "ber": "D",
      "interest_rate_pct": 3.6,
      "aprc_pct": 3.9,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": 250000,
      "notes": []
    },
    {
      "id": "hvm.7y.e",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "high_value_fixed",
      "term_years": 7,
      "ber": "E",
      "interest_rate_pct": 3.65,
      "aprc_pct": 3.9,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": 250000,
      "notes": []
    },
    {
      "id": "hvm.7y.f",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "high_value_fixed",
      "term_years": 7,
      "ber": "F",
      "interest_rate_pct": 3.7,
      "aprc_pct": 4,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": 250000,
      "notes": []
    },
    {
      "id": "hvm.7y.g",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "high_value_fixed",
      "term_years": 7,
      "ber": "G",
      "interest_rate_pct": 3.75,
      "aprc_pct": 4,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": 250000,
      "notes": []
    },
    {
      "id": "hvm.7y.ber_exempt",
      "customer_types": [
        "first_time_buyer",
        "switcher",
        "mover"
      ],
      "rate_family": "high_value_fixed",
      "term_years": 7,
      "ber": "BER Exempt",
      "interest_rate_pct": 3.8,
      "aprc_pct": 4,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": 250000,
      "notes": []
    },
    {
      "id": "variable.owner_occupier.first_time_buyer",
      "customer_types": [
        "first_time_buyer"
      ],
      "rate_family": "standard_variable",
      "term_years": null,
      "ber": "any",
      "interest_rate_pct": 4.15,
      "aprc_pct": 4.3,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": null,
      "notes": [
        "Variable rate may rise or fall."
      ]
    },
    {
      "id": "variable.owner_occupier.switcher",
      "customer_types": [
        "switcher"
      ],
      "rate_family": "standard_variable",
      "term_years": null,
      "ber": "any",
      "interest_rate_pct": 4.15,
      "aprc_pct": 4.3,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": null,
      "notes": [
        "Variable rate may rise or fall."
      ]
    },
    {
      "id": "variable.owner_occupier.mover",
      "customer_types": [
        "mover"
      ],
      "rate_family": "standard_variable",
      "term_years": null,
      "ber": "any",
      "interest_rate_pct": 4.15,
      "aprc_pct": 4.3,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": null,
      "notes": [
        "Variable rate may rise or fall."
      ]
    },
    {
      "id": "existing.1y.a",
      "customer_types": [
        "existing_boi_mortgage"
      ],
      "rate_family": "existing_fixed",
      "term_years": 1,
      "ber": "A",
      "interest_rate_pct": 3.3,
      "aprc_pct": 4.2,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "existing.1y.b",
      "customer_types": [
        "existing_boi_mortgage"
      ],
      "rate_family": "existing_fixed",
      "term_years": 1,
      "ber": "B",
      "interest_rate_pct": 3.35,
      "aprc_pct": 4.2,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "existing.1y.c",
      "customer_types": [
        "existing_boi_mortgage"
      ],
      "rate_family": "existing_fixed",
      "term_years": 1,
      "ber": "C",
      "interest_rate_pct": 3.4,
      "aprc_pct": 4.2,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "existing.1y.d",
      "customer_types": [
        "existing_boi_mortgage"
      ],
      "rate_family": "existing_fixed",
      "term_years": 1,
      "ber": "D",
      "interest_rate_pct": 3.45,
      "aprc_pct": 4.2,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "existing.1y.e",
      "customer_types": [
        "existing_boi_mortgage"
      ],
      "rate_family": "existing_fixed",
      "term_years": 1,
      "ber": "E",
      "interest_rate_pct": 3.5,
      "aprc_pct": 4.2,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "existing.1y.f",
      "customer_types": [
        "existing_boi_mortgage"
      ],
      "rate_family": "existing_fixed",
      "term_years": 1,
      "ber": "F",
      "interest_rate_pct": 3.55,
      "aprc_pct": 4.2,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "existing.1y.g",
      "customer_types": [
        "existing_boi_mortgage"
      ],
      "rate_family": "existing_fixed",
      "term_years": 1,
      "ber": "G",
      "interest_rate_pct": 3.6,
      "aprc_pct": 4.2,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "existing.1y.ber_exempt",
      "customer_types": [
        "existing_boi_mortgage"
      ],
      "rate_family": "existing_fixed",
      "term_years": 1,
      "ber": "BER Exempt",
      "interest_rate_pct": 3.65,
      "aprc_pct": 4.2,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "existing.2y.a",
      "customer_types": [
        "existing_boi_mortgage"
      ],
      "rate_family": "existing_fixed",
      "term_years": 2,
      "ber": "A",
      "interest_rate_pct": 3.3,
      "aprc_pct": 4.1,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "existing.2y.b",
      "customer_types": [
        "existing_boi_mortgage"
      ],
      "rate_family": "existing_fixed",
      "term_years": 2,
      "ber": "B",
      "interest_rate_pct": 3.35,
      "aprc_pct": 4.1,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "existing.2y.c",
      "customer_types": [
        "existing_boi_mortgage"
      ],
      "rate_family": "existing_fixed",
      "term_years": 2,
      "ber": "C",
      "interest_rate_pct": 3.4,
      "aprc_pct": 4.1,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "existing.2y.d",
      "customer_types": [
        "existing_boi_mortgage"
      ],
      "rate_family": "existing_fixed",
      "term_years": 2,
      "ber": "D",
      "interest_rate_pct": 3.45,
      "aprc_pct": 4.1,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "existing.2y.e",
      "customer_types": [
        "existing_boi_mortgage"
      ],
      "rate_family": "existing_fixed",
      "term_years": 2,
      "ber": "E",
      "interest_rate_pct": 3.5,
      "aprc_pct": 4.1,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "existing.2y.f",
      "customer_types": [
        "existing_boi_mortgage"
      ],
      "rate_family": "existing_fixed",
      "term_years": 2,
      "ber": "F",
      "interest_rate_pct": 3.55,
      "aprc_pct": 4.1,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "existing.2y.g",
      "customer_types": [
        "existing_boi_mortgage"
      ],
      "rate_family": "existing_fixed",
      "term_years": 2,
      "ber": "G",
      "interest_rate_pct": 3.6,
      "aprc_pct": 4.1,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "existing.2y.ber_exempt",
      "customer_types": [
        "existing_boi_mortgage"
      ],
      "rate_family": "existing_fixed",
      "term_years": 2,
      "ber": "BER Exempt",
      "interest_rate_pct": 3.65,
      "aprc_pct": 4.1,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "existing.3y.a",
      "customer_types": [
        "existing_boi_mortgage"
      ],
      "rate_family": "existing_fixed",
      "term_years": 3,
      "ber": "A",
      "interest_rate_pct": 3.4,
      "aprc_pct": 4,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "existing.3y.b",
      "customer_types": [
        "existing_boi_mortgage"
      ],
      "rate_family": "existing_fixed",
      "term_years": 3,
      "ber": "B",
      "interest_rate_pct": 3.45,
      "aprc_pct": 4,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "existing.3y.c",
      "customer_types": [
        "existing_boi_mortgage"
      ],
      "rate_family": "existing_fixed",
      "term_years": 3,
      "ber": "C",
      "interest_rate_pct": 3.5,
      "aprc_pct": 4,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "existing.3y.d",
      "customer_types": [
        "existing_boi_mortgage"
      ],
      "rate_family": "existing_fixed",
      "term_years": 3,
      "ber": "D",
      "interest_rate_pct": 3.55,
      "aprc_pct": 4.1,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "existing.3y.e",
      "customer_types": [
        "existing_boi_mortgage"
      ],
      "rate_family": "existing_fixed",
      "term_years": 3,
      "ber": "E",
      "interest_rate_pct": 3.6,
      "aprc_pct": 4.1,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "existing.3y.f",
      "customer_types": [
        "existing_boi_mortgage"
      ],
      "rate_family": "existing_fixed",
      "term_years": 3,
      "ber": "F",
      "interest_rate_pct": 3.65,
      "aprc_pct": 4.1,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "existing.3y.g",
      "customer_types": [
        "existing_boi_mortgage"
      ],
      "rate_family": "existing_fixed",
      "term_years": 3,
      "ber": "G",
      "interest_rate_pct": 3.7,
      "aprc_pct": 4.1,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "existing.3y.ber_exempt",
      "customer_types": [
        "existing_boi_mortgage"
      ],
      "rate_family": "existing_fixed",
      "term_years": 3,
      "ber": "BER Exempt",
      "interest_rate_pct": 3.75,
      "aprc_pct": 4.1,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "existing.4y.a",
      "customer_types": [
        "existing_boi_mortgage"
      ],
      "rate_family": "existing_fixed",
      "term_years": 4,
      "ber": "A",
      "interest_rate_pct": 3.1,
      "aprc_pct": 3.8,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "existing.4y.b",
      "customer_types": [
        "existing_boi_mortgage"
      ],
      "rate_family": "existing_fixed",
      "term_years": 4,
      "ber": "B",
      "interest_rate_pct": 3.15,
      "aprc_pct": 3.8,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "existing.4y.c",
      "customer_types": [
        "existing_boi_mortgage"
      ],
      "rate_family": "existing_fixed",
      "term_years": 4,
      "ber": "C",
      "interest_rate_pct": 3.2,
      "aprc_pct": 3.9,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "existing.4y.d",
      "customer_types": [
        "existing_boi_mortgage"
      ],
      "rate_family": "existing_fixed",
      "term_years": 4,
      "ber": "D",
      "interest_rate_pct": 3.25,
      "aprc_pct": 3.9,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "existing.4y.e",
      "customer_types": [
        "existing_boi_mortgage"
      ],
      "rate_family": "existing_fixed",
      "term_years": 4,
      "ber": "E",
      "interest_rate_pct": 3.3,
      "aprc_pct": 3.9,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "existing.4y.f",
      "customer_types": [
        "existing_boi_mortgage"
      ],
      "rate_family": "existing_fixed",
      "term_years": 4,
      "ber": "F",
      "interest_rate_pct": 3.35,
      "aprc_pct": 3.9,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "existing.4y.g",
      "customer_types": [
        "existing_boi_mortgage"
      ],
      "rate_family": "existing_fixed",
      "term_years": 4,
      "ber": "G",
      "interest_rate_pct": 3.4,
      "aprc_pct": 3.9,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "existing.4y.ber_exempt",
      "customer_types": [
        "existing_boi_mortgage"
      ],
      "rate_family": "existing_fixed",
      "term_years": 4,
      "ber": "BER Exempt",
      "interest_rate_pct": 3.45,
      "aprc_pct": 4,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "existing.5y.a",
      "customer_types": [
        "existing_boi_mortgage"
      ],
      "rate_family": "existing_fixed",
      "term_years": 5,
      "ber": "A",
      "interest_rate_pct": 3.4,
      "aprc_pct": 3.9,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "existing.5y.b",
      "customer_types": [
        "existing_boi_mortgage"
      ],
      "rate_family": "existing_fixed",
      "term_years": 5,
      "ber": "B",
      "interest_rate_pct": 3.45,
      "aprc_pct": 3.9,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "existing.5y.c",
      "customer_types": [
        "existing_boi_mortgage"
      ],
      "rate_family": "existing_fixed",
      "term_years": 5,
      "ber": "C",
      "interest_rate_pct": 3.5,
      "aprc_pct": 3.9,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "existing.5y.d",
      "customer_types": [
        "existing_boi_mortgage"
      ],
      "rate_family": "existing_fixed",
      "term_years": 5,
      "ber": "D",
      "interest_rate_pct": 3.55,
      "aprc_pct": 4,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "existing.5y.e",
      "customer_types": [
        "existing_boi_mortgage"
      ],
      "rate_family": "existing_fixed",
      "term_years": 5,
      "ber": "E",
      "interest_rate_pct": 3.6,
      "aprc_pct": 4,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "existing.5y.f",
      "customer_types": [
        "existing_boi_mortgage"
      ],
      "rate_family": "existing_fixed",
      "term_years": 5,
      "ber": "F",
      "interest_rate_pct": 3.65,
      "aprc_pct": 4,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "existing.5y.g",
      "customer_types": [
        "existing_boi_mortgage"
      ],
      "rate_family": "existing_fixed",
      "term_years": 5,
      "ber": "G",
      "interest_rate_pct": 3.7,
      "aprc_pct": 4,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "existing.5y.ber_exempt",
      "customer_types": [
        "existing_boi_mortgage"
      ],
      "rate_family": "existing_fixed",
      "term_years": 5,
      "ber": "BER Exempt",
      "interest_rate_pct": 3.75,
      "aprc_pct": 4.1,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "existing.10y.a",
      "customer_types": [
        "existing_boi_mortgage"
      ],
      "rate_family": "existing_fixed",
      "term_years": 10,
      "ber": "A",
      "interest_rate_pct": 3.7,
      "aprc_pct": 3.9,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "existing.10y.b",
      "customer_types": [
        "existing_boi_mortgage"
      ],
      "rate_family": "existing_fixed",
      "term_years": 10,
      "ber": "B",
      "interest_rate_pct": 3.75,
      "aprc_pct": 3.9,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "existing.10y.c",
      "customer_types": [
        "existing_boi_mortgage"
      ],
      "rate_family": "existing_fixed",
      "term_years": 10,
      "ber": "C",
      "interest_rate_pct": 3.8,
      "aprc_pct": 4,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "existing.10y.d",
      "customer_types": [
        "existing_boi_mortgage"
      ],
      "rate_family": "existing_fixed",
      "term_years": 10,
      "ber": "D",
      "interest_rate_pct": 3.85,
      "aprc_pct": 4,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "existing.10y.e",
      "customer_types": [
        "existing_boi_mortgage"
      ],
      "rate_family": "existing_fixed",
      "term_years": 10,
      "ber": "E",
      "interest_rate_pct": 3.9,
      "aprc_pct": 4.1,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "existing.10y.f",
      "customer_types": [
        "existing_boi_mortgage"
      ],
      "rate_family": "existing_fixed",
      "term_years": 10,
      "ber": "F",
      "interest_rate_pct": 3.95,
      "aprc_pct": 4.1,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "existing.10y.g",
      "customer_types": [
        "existing_boi_mortgage"
      ],
      "rate_family": "existing_fixed",
      "term_years": 10,
      "ber": "G",
      "interest_rate_pct": 4,
      "aprc_pct": 4.1,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "existing.10y.ber_exempt",
      "customer_types": [
        "existing_boi_mortgage"
      ],
      "rate_family": "existing_fixed",
      "term_years": 10,
      "ber": "BER Exempt",
      "interest_rate_pct": 4.05,
      "aprc_pct": 4.2,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "existing.variable",
      "customer_types": [
        "existing_boi_mortgage"
      ],
      "rate_family": "standard_variable",
      "term_years": null,
      "ber": "any",
      "interest_rate_pct": 4.15,
      "aprc_pct": 4.3,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "btl.2y.a",
      "customer_types": [
        "buy_to_let_new"
      ],
      "rate_family": "buy_to_let_fixed",
      "term_years": 2,
      "ber": "A",
      "interest_rate_pct": 5.65,
      "aprc_pct": 6,
      "cashback": {
        "eligible": true,
        "structure": "2% on qualifying new buy-to-let fixed-rate drawdown"
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "btl.2y.b",
      "customer_types": [
        "buy_to_let_new"
      ],
      "rate_family": "buy_to_let_fixed",
      "term_years": 2,
      "ber": "B",
      "interest_rate_pct": 5.7,
      "aprc_pct": 6,
      "cashback": {
        "eligible": true,
        "structure": "2% on qualifying new buy-to-let fixed-rate drawdown"
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "btl.2y.c",
      "customer_types": [
        "buy_to_let_new"
      ],
      "rate_family": "buy_to_let_fixed",
      "term_years": 2,
      "ber": "C",
      "interest_rate_pct": 5.75,
      "aprc_pct": 6.1,
      "cashback": {
        "eligible": true,
        "structure": "2% on qualifying new buy-to-let fixed-rate drawdown"
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "btl.2y.d",
      "customer_types": [
        "buy_to_let_new"
      ],
      "rate_family": "buy_to_let_fixed",
      "term_years": 2,
      "ber": "D",
      "interest_rate_pct": 5.8,
      "aprc_pct": 6.1,
      "cashback": {
        "eligible": true,
        "structure": "2% on qualifying new buy-to-let fixed-rate drawdown"
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "btl.2y.e",
      "customer_types": [
        "buy_to_let_new"
      ],
      "rate_family": "buy_to_let_fixed",
      "term_years": 2,
      "ber": "E",
      "interest_rate_pct": 5.85,
      "aprc_pct": 6.2,
      "cashback": {
        "eligible": true,
        "structure": "2% on qualifying new buy-to-let fixed-rate drawdown"
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "btl.2y.f",
      "customer_types": [
        "buy_to_let_new"
      ],
      "rate_family": "buy_to_let_fixed",
      "term_years": 2,
      "ber": "F",
      "interest_rate_pct": 5.9,
      "aprc_pct": 6.3,
      "cashback": {
        "eligible": true,
        "structure": "2% on qualifying new buy-to-let fixed-rate drawdown"
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "btl.2y.g",
      "customer_types": [
        "buy_to_let_new"
      ],
      "rate_family": "buy_to_let_fixed",
      "term_years": 2,
      "ber": "G",
      "interest_rate_pct": 5.95,
      "aprc_pct": 6.3,
      "cashback": {
        "eligible": true,
        "structure": "2% on qualifying new buy-to-let fixed-rate drawdown"
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "btl.2y.ber_exempt",
      "customer_types": [
        "buy_to_let_new"
      ],
      "rate_family": "buy_to_let_fixed",
      "term_years": 2,
      "ber": "BER Exempt",
      "interest_rate_pct": 6,
      "aprc_pct": 6.4,
      "cashback": {
        "eligible": true,
        "structure": "2% on qualifying new buy-to-let fixed-rate drawdown"
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "btl.5y.a",
      "customer_types": [
        "buy_to_let_new"
      ],
      "rate_family": "buy_to_let_fixed",
      "term_years": 5,
      "ber": "A",
      "interest_rate_pct": 5.8,
      "aprc_pct": 6.1,
      "cashback": {
        "eligible": true,
        "structure": "2% on qualifying new buy-to-let fixed-rate drawdown"
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "btl.5y.b",
      "customer_types": [
        "buy_to_let_new"
      ],
      "rate_family": "buy_to_let_fixed",
      "term_years": 5,
      "ber": "B",
      "interest_rate_pct": 5.85,
      "aprc_pct": 6.2,
      "cashback": {
        "eligible": true,
        "structure": "2% on qualifying new buy-to-let fixed-rate drawdown"
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "btl.5y.c",
      "customer_types": [
        "buy_to_let_new"
      ],
      "rate_family": "buy_to_let_fixed",
      "term_years": 5,
      "ber": "C",
      "interest_rate_pct": 5.9,
      "aprc_pct": 6.3,
      "cashback": {
        "eligible": true,
        "structure": "2% on qualifying new buy-to-let fixed-rate drawdown"
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "btl.5y.d",
      "customer_types": [
        "buy_to_let_new"
      ],
      "rate_family": "buy_to_let_fixed",
      "term_years": 5,
      "ber": "D",
      "interest_rate_pct": 5.95,
      "aprc_pct": 6.3,
      "cashback": {
        "eligible": true,
        "structure": "2% on qualifying new buy-to-let fixed-rate drawdown"
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "btl.5y.e",
      "customer_types": [
        "buy_to_let_new"
      ],
      "rate_family": "buy_to_let_fixed",
      "term_years": 5,
      "ber": "E",
      "interest_rate_pct": 6,
      "aprc_pct": 6.4,
      "cashback": {
        "eligible": true,
        "structure": "2% on qualifying new buy-to-let fixed-rate drawdown"
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "btl.5y.f",
      "customer_types": [
        "buy_to_let_new"
      ],
      "rate_family": "buy_to_let_fixed",
      "term_years": 5,
      "ber": "F",
      "interest_rate_pct": 6.05,
      "aprc_pct": 6.4,
      "cashback": {
        "eligible": true,
        "structure": "2% on qualifying new buy-to-let fixed-rate drawdown"
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "btl.5y.g",
      "customer_types": [
        "buy_to_let_new"
      ],
      "rate_family": "buy_to_let_fixed",
      "term_years": 5,
      "ber": "G",
      "interest_rate_pct": 6.1,
      "aprc_pct": 6.5,
      "cashback": {
        "eligible": true,
        "structure": "2% on qualifying new buy-to-let fixed-rate drawdown"
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "btl.5y.ber_exempt",
      "customer_types": [
        "buy_to_let_new"
      ],
      "rate_family": "buy_to_let_fixed",
      "term_years": 5,
      "ber": "BER Exempt",
      "interest_rate_pct": 6.15,
      "aprc_pct": 6.5,
      "cashback": {
        "eligible": true,
        "structure": "2% on qualifying new buy-to-let fixed-rate drawdown"
      },
      "minimum_mortgage_amount_eur": null,
      "notes": []
    },
    {
      "id": "btl.variable",
      "customer_types": [
        "buy_to_let_new"
      ],
      "rate_family": "buy_to_let_variable",
      "term_years": null,
      "ber": "any",
      "interest_rate_pct": 4.85,
      "aprc_pct": 5.1,
      "cashback": {
        "eligible": false
      },
      "minimum_mortgage_amount_eur": null,
      "notes": [
        "Maximum loan generally 70% of property value according to BOI public legal notice."
      ]
    }
  ]
} as const satisfies MortgageRateCatalogue
