/**
 * Turns the BOI mortgage-rates zip into a TypeScript module.
 *
 * Generated for the same reason the product knowledge base is: `_shared` compiles under Deno
 * and under Vite, and a JSON import behaves differently in each. A .ts file behaves the same in
 * both, and the double-compile is checked by `npm run typecheck` plus `deno check`.
 *
 *   node scripts/generate-mortgage-rates.ts <extracted-rates-dir>
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const source = process.argv[2]
if (!source) {
  console.error('usage: node scripts/generate-mortgage-rates.ts <extracted-rates-dir>')
  process.exit(1)
}

const data = JSON.parse(readFileSync(join(source, 'boi-mortgage-rates.json'), 'utf8')) as {
  metadata: { retrieved_on: string; public_rates_table_last_update: string }
  rates: readonly unknown[]
}

const out = `// GENERATED by scripts/generate-mortgage-rates.ts — do not edit by hand.
//
// Bank of Ireland's published mortgage rate table, read from their site on
// ${data.metadata.retrieved_on}. The table labels its own last update as
// ${data.metadata.public_rates_table_last_update}, and that date is carried through to
// everything Baz says about a rate: a figure without an as-of is a figure nobody can check.
//
// ${String(data.rates.length)} rows, because a rate here is a function of four things at once —
// who the customer is, the BER of the property, the term, and how much they are borrowing.
// Picking the right one is \`selectRates\` in \`mortgage-rates-select.ts\`, deliberately not
// something the model does by reading a table.

import type { MortgageRateCatalogue } from './mortgage-rate-types.ts'

export const boiMortgageRates = ${JSON.stringify(data, null, 2)} as const satisfies MortgageRateCatalogue
`

writeFileSync(
  'supabase/functions/_shared/tenants/boi/mortgage-rates.ts',
  out.replace(/\r\n/g, '\n'),
)
console.log(`wrote ${String(data.rates.length)} rates`)
