/**
 * Turns the BOI knowledge-base zip into a TypeScript module.
 *
 * Generated rather than imported: `_shared/domain` and the Edge Functions compile under Deno and
 * under Vite, and a JSON import behaves differently in each. A .ts file behaves the same in both,
 * and the double-compile is checked by `npm run typecheck` plus `deno check`.
 *
 *   node scripts/generate-product-kb.ts <extracted-kb-dir>
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const source = process.argv[2]
if (!source) {
  console.error('usage: node scripts/generate-product-kb.ts <extracted-kb-dir>')
  process.exit(1)
}

/* Shaped only as far as this script needs; `kb-types.ts` is where the real shape is enforced,
   and `deno check` on the generated file is what enforces it. */
const kb = JSON.parse(
  readFileSync(join(source, 'boi-retail-product-knowledge-base.json'), 'utf8'),
) as { metadata: { as_of: string }; products: readonly unknown[] }

const out = `// GENERATED by scripts/generate-product-kb.mjs — do not edit by hand.
//
// Bank of Ireland's public Irish retail offering, read from their personal-banking site and
// verified on ${kb.metadata.as_of}. Real, published information — which is a change from the
// invented catalogue this replaced, and the reason the disclaimer in \`products.ts\` now says
// what it does.
//
// NOT authoritative for anything that moves: live rates, APR/APRC, mortgage rate tables,
// insurance premiums, promotions, scheme availability, or any eligibility decision. The pack
// says so itself, and \`freshnessClass\` carries it per product.

import type { KnowledgeBase } from './kb-types.ts'

export const boiKnowledgeBase = ${JSON.stringify(kb, null, 2)} as const satisfies KnowledgeBase
`

writeFileSync('supabase/functions/_shared/tenants/boi/knowledge-base.ts', out)
console.log(`wrote ${kb.products.length} products, ${(out.length / 1024).toFixed(0)} kB`)
